### ISSUE TITLE
allow toggle between community and public sites

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#186]
child of #106
requires #184

**Comment by mattia-io** [comment]
Hey boys,

Yhe I thought the behaviour here was clear, that's why I didn't comment explanations. The behaviour is just like you've described @BenGamma with the addition that on https://onearmy.world there is a big button "go to community" (temporary text :) that will bring both logged in and not logged in users to https://community.onearmy.world

Any more info needed here?

**Comment by BenGamma** [comment]
Gotcha, I was looking for the link to the mockups, but just found it 😅 https://drive.google.com/drive/u/0/folders/1OyJmh39ojHJxs6otETNkYvDUVpAh-3aN

In a close futur we will probably want to onboard user with the user login procedure after clicking on the "go to community" button.

But for now what we'll do is :
* display the Public site on *onearmy.world*
* on click on "go to community" button, redirect to *community.onearmy.world* subdomain
* To display the associated page & navigation depending on the subdomain you can found an example in `src/pages/index.tsx`

**Comment by chrismclarke** [comment]
we're quite a way off implementing this so closing for now
