### ISSUE TITLE
[research] location search component

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#208]
In the next weeks/month we'll need to build a search engine for location.

Here is a glimps of how we want it to be (taken from eventbrite.com) :
![location-search](https://user-images.githubusercontent.com/4993215/50975865-d7fd8980-14ee-11e9-8658-a02fd74a0bc3.gif)

Purpose of this thread is to share opinions on this feature and found the best solution available out there to make it.

Maybe @SpaceK33z you'll have some suggestions ?

**Comment by chrismclarke** [comment]
I think I would recommend going with Algolia so we can have things up and running quickly (they also have react components), and if we find ouselves quickly exhausting free quotas and project very high billing we could look to implement our own server in a similar way

**Comment by nzchicken** [comment]
I used maptiler.com api for the map.preciousplastic.com in the past since it was free. It works pretty quickly, and I actually built a debounced text input search for it here: https://github.com/hakkens/precious-plastic-map/blob/master/src/js/map/search.js

Of course, makes sense to use Algolia if going that way on #210, but just another option for interests sake

**Comment by nzchicken** [comment]
https://www.npmjs.com/package/algolia-places-react <-- bettteerrrr

**Comment by chrismclarke** [comment]
Agreed, saves having to build a wrapper ourselves

**Comment by chrismclarke** [comment]
merge into #143
