### ISSUE TITLE
[research] search engine

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#210]
The purpose of this thread is to share opinions on this feature and found the best solution available out there to make it.

We are building a search engine to easily access all the knowledge of the plateform, discussions, Q&A posts, etc.

What solutions to explore I know :
* [Algolia](https://www.algolia.com) build a good tool, well appreciated in the whole community. It's free to use for open source project.
* [Elastic search](https://www.elastic.co/fr/), that runs on your own dedicated server.

For the rest I'm open to suggestions 😌

**Comment by chrismclarke** [comment]
I've used elasticsearch before, it is good but the technical setup would feel very much overkill for what we want - typically you need a cluster of 3 dedicated servers to handle the various nodes and shards, and even if these were micro machines you'd be looking at a minimum of $15 per month just to run. 

I was looking a bit into algolia the other day I really liked the look of it. I was initially worried whether they needed to do everything through site indexing (which wouldn't work on ours unless we also looked into something like next.js to render static pages or an advanced sitemap linked to the db... which we may still want at a later stage for seo), but looks like they support pushing data from a db too.

I would definitely suggest that the work involved would be reasonably complex, but that's never stopped us before!

**Comment by nzchicken** [comment]
I've just done a quick bit of research on this one too, looks like Algolia is a good option:
- https://medium.com/@matayoshi.mariano/elasticsearch-vs-algolia-96364f5567a3 <-- Algolia vs Elastic Search/Solar. Alogia is recommended for smaller (400k records) implementations - which fits us for now.
- https://opensourceconnections.com/blog/2016/06/01/thoughts-on-algolia/ <-- More positive support for Algolia

If going the ElasticSearch Route, my recommendation would be to use ElasticCloud so that it doesn't have to be managed as much, but that comes with the cost per month as Chris said, and no real benefit for now (Would be cheaper in the long run with more records etc).

Both solutions support the same workflow which is pretty much as follows:
- Setup search appliance to index the records in the way you want. i.e. tag the data with title, description, tags/categories - anything that makes it easier to filter the results (this helps with the results later)
- On a backend side, as soon as a record lands, push it off to the search appliance to index
- On a frontend side, use the provided APIs or SDKs to call the search appliance directly to get the results you need. Use the results to display on the page, go on with your sweet life.

But yes, recommendation is Algolia for now. There doesn't look like many other alternatives, and it should be somewhat okay to shift to another service later if it makes sense, assuming you treat the search as an external service which you call to index, and call to search.

**Comment by chrismclarke** [comment]
Going to try implementation with algolia, closing
