### ISSUE TITLE
[research] markdown form input

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#211]
The purpose of this thread is to share opinions on this feature and found the best solution available out there to make it.

We want the user to be able to comment using markdown or an editor, like this github comment form, to make the font **bold** or _italic_, create points, title, add citations, links.

What I know :
* As an editor we could use [react-mde](https://github.com/andrerpena/react-mde) for the editor, wich is based on facebook's [draft library](https://draftjs.org/).
* to read the markdown we could use [react-markdown](https://rexxars.github.io/react-markdown/).

The goal here is to test to implement these solutions in our current code base and see which one fits the best for our needs 💯

**Comment by chrismclarke** [comment]
ah cool, I had mentioned this in #209 but see it's covered here. Given the fairly general target audience I agree the most important thing is a simple set of buttons users can use instead of writing code. 

I just took a look at react-mde and it says the repo is undergoing breaking changes. I imagine draft receives much better support and is more stable, so unless we have specific reason to prefer markdown over html (assuming the user won't be writing code in either case) then I would suggest just go for draft.

**Comment by tx4x** [comment]
well, as long-term power user I'd really want to use markdown anywhere. there are quite a few user friendly markdown editors out there which have the standard buttons out there.

it has been a couple of times i dropped the idea to write a proper article on pp forum because of that. 
also, by supporting markdown you enable users to write their articles elsewhere too.

**Comment by BenGamma** [comment]
@tx4x markdown would be nice yes. Do you have any recommandations on a markdown library we could use ?
Cherries on the cake would be a working example component 😍

**Comment by tx4x** [comment]
I have not used this myself but it seems the most fitted : http://nhnent.github.io/tui.editor/api/latest/tutorial-example13-all-extension-blank.html (main page : https://ui.toast.com/tui-editor/). It's using bloody jQuery and whatever mud but in terms of output and documentation it's quite well. however with a size of 1.2 MB it's darn heavy, and still you need a mobile friendly version though... if you like this one, i can wrap it up into a react/ts/material-io component. 

i will check this evening again for more candidates.

**Comment by tx4x** [comment]
neat : https://jpuri.github.io/react-draft-wysiwyg/#/

**Comment by BenGamma** [comment]
[React Draft Wysiwyg](https://jpuri.github.io/react-draft-wysiwyg/#/) sound like a strong candidate. Thanks for sharing 🖖

**Comment by tx4x** [comment]
you're welcome, if you need help with integrating this in the codebase (custom formatters, actions/commands), let me know ( i have a long history writing rich editors ). I can write a few pages about what should be in the editor when it comes to precious plastic discussions :-)

**Comment by BenGamma** [comment]
Yes we'll probably need some custom integration at some point, thanks for asking 👍 

For now what would be nice to have is a working example of React Draft Wysiwyg integrated in the project.
If you want to go further I suggest you create a branch from `master` and from there create a working example on a new url (for example if I visit `/discussions/post/<slug>`, the editor is displayed and we can console.log the submited data)

**Comment by tx4x** [comment]
just to add a few more good points: 

- markdown makes it all portable (gists, wikis), easy to re-compile a curated list of posts into a versioned wiki article.
- with being portable, also exchange formats become a piece of cake : PDF, etc...

it's true, to wrap one of these editors up isn't much work at all, what's more difficult is the protocol in place to add other content in the same post, ie: embed/quote a piece from another post. there has to be a good API in place to feed the editor with all sort's of things, auto completion for tags, content, users, machine catalog (user versions, components, sources,...). not sure how you go with the backend but i guess there will be something like elastic search behind some api (swagger!?). as soon this things are clear i think it's then straightforward to implement all those new editor commands and aids (auto-completion).

beside the pretty common editor functionality, regarding PP needs, I will post a list here soon but one thing seems clear to me: i'd love that users can maintain their own 'space', ie: a catalog of products, machines, ideas, etc... and post references to that content anywhere. there are so many good ideas which are pretty much lost in the current forum, so many stuff could have affect a next and truly community powered version more nicely and effective... possibly i am dreaming. 

so about making the first wrapper for this 'draft' thing, np! I can do that til monday. but as said, having more input about the content query API or anything editor protocol related would be very helpful. if you have a look at VSCode, there is generic editor protocol in place, it makes sense to borrow these concepts/contracts though

**Comment by chrismclarke** [comment]
Good point about referencing quoting other messages, I hadn't thought about that... There will also be things like @mentions to think about. We will need to talk with @mattia-io to better decide how we want the users to interact before taking the dev too far (e.g. would messages all be displayed in a list, nested chats, seperate threads, quotes etc.)... I'm assuming the answer will vary for our different use cases.

For the first implementation I think the backend is mostly just a set of fields within the database (firestore) entry. We would later want to build apis on top of this, cloud functions already has the functionality to observe database changes (e.g. new comment added with fields x,y,z), and then we could look into building various microservices like email/push notifications etc. I think we're currently planning to implement Algolia for search.

Dream on. Anything is possible.

**Comment by tx4x** [comment]
right, thanks for the insights. didn't even know that mattio is doing code :-)

btw. editing is one thing, you more likely need also a 'viewer' which is SSR able. I used '[showdown](https://github.com/showdownjs/showdown)' no idea what's good nowadays, anything which support github flavour would be nice though. this part however can become fast tricky btw

**Comment by mattia-io** [comment]
Hey everyone, thanks for all the inputs. 
It's now officially in my list to be discussed with Dave and UX. 
Will update soon on this. 

@chrismclarke in regards to user interaction we have 3 posting types:

**How-to:** 
Author posts the **How-To** with all the different steps (no comments on individual steps). Users and the author can comment below the **How-To** and nested reply to comments. 

**Discussion**
Author posts the topic/discussion. Users and the author can comment back and forth and nested reply to comments. 

**Q&A**
Author posts the question. Users can comment their answers below (author cannot post answers). Users and author can nested reply to comment. Author can choose an answer to be the correct one. 

Hope this clarifies it a bit.
Let me know if still unclear.

**Comment by chrismclarke** [comment]
Awesome, Crystal (ish).
Brief follow-up:
1. How many of these places do we want people to be able to edit their original comment? All? If so would we want to mark with the word 'edited' or keep track of the old comment also?
2. In terms of sorting do is chronological by sufficient, or would you also want to be able to swap between most commented/replied, most recently updated etc? (none of these too difficult as long as we have the data structured correctly to begin with)
3. Once the Q&A author has marked a correct/useful response should the thread be locked? (but maybe still allow for direct response to the chose solution?)

**Comment by mattia-io** [comment]
Hey yo,

1. Added to my query list for UX
2. Chronological / Most Useful / Most replies
3. Added to my query list for UX

Peace 👀

**Comment by tx4x** [comment]
hi,
so I've done only little research regarding the draftjs-react editor ('react-draft-wysiwyg') implementation :

- i need to know in which modules you want to have it, I guess you want the same editor everywhere of course but let me know if there is something else

- since there are more likely custom tags to be resolved (ie: quote another message, embed post, internal links, etc...) the choice of the markdown/post display goes hand in hand with the editor since they need the same 'resolver' contract. from what i see, the most simple is to extend '[showdown](https://github.com/showdownjs/showdown)'. the shared functionality between editor and display (convert to html) can be simplified to a small protocol & implementation. 

- what puzzles me is to index then the user posts/comments, it also requires quite some thoughts. 

for now, i can contribute the required interfaces (TypeScript) to start implementing some prototype. at this point you should be able to spot problems or required leg-work first

**Comment by tx4x** [comment]
@chrismclarke , gotcha, will bump into the module-discussion branch this week, first as stand-alone component, so we are wiring it up when all is done (needs mocks of course).

**Comment by tx4x** [comment]
bad news. none of the editors mentioned here gives you a really nice experience. they're all miles behind like CK editor or such. there is also no out of the box wysiwyg markdown editor which does all as expected. the only real compromise i see currently is to have a 'simple' version (input/output : html) and an advanced version (dual view : markdown with preview) with input = markdown and output = html (showdown)

'react-draft-wysiwyg draft-js' in action : 
![image](https://user-images.githubusercontent.com/1205100/51843351-111d6280-2313-11e9-837d-5df034fc92cc.png)
sucks, really odd to use.

**Comment by chrismclarke** [comment]
Could you explain a bit more what you mean by the experience sucks so we can know what your thoughts expectations are, and help decide also what the mvp for the community should include (separate out 'must haves' and 'nice-to-haves'). From the screenshot it looks like a pretty standard editor...

**Comment by tx4x** [comment]
well, try yourself here https://jpuri.github.io/react-draft-wysiwyg/# . For instance add an image, try to resize or move it around after inserting. This feels like middle age compared to proper setup of TinyMCE (which is in TS btw.)

feature list : ok, hang tight, I will put something together but in short : all what you can see in TinyMCE (apart from advanced styling) : image handling : size, position, etc...

features also vary on your needs though: you want let users write proper multi-page articles, etc...

**Comment by chrismclarke** [comment]
Really useful, thanks a lot! @mattia-io , you might also want to take a look and add your input.

From my side I would have the following points:
1. Agree standard text editor, would suggest not custom fonts as we'd rather keep things looking more uniform and not have the extra font-loading overheads.
2. I hadn't thought about tables but could see how they would be useful for research data so would think worth keeping
3. Images I would also suggest youtube embeds. I would strongly suggest no fancy editing or resizing for images though, we don't want to have to rely on users to make sure an image doesn't take up the whole screen. Instead we would have specific dimensions on all images (probably reasonably small with ability to view full on click). You have extra problem when trying to resize images because essentially you need to send the image to the database alongside styles objects (or all as inline html, markdown would struggle here), and then you can get new dom sanitization issues as you try to inject it back into the javascript template (fine on static server-rendered content, browsers less consistent on dynamic).
4. Links - as in hrefs? if so agree and imagine comes pretty standard. Bespoke links to things like other comments and automatic snippets might be tricker.
5. Mentions - think it would be a really nice-to-have, but I don't think I would push it as high up the priority list (people can still write thanks @whoever and people will get the gist, it only becomes of benefit when we have a decent notification system to let you know when you've got mentions etc., and even then you will likely still be happy with updates on the entire feed (like any thread on github))
6. Tags - I think this is a 'must-have' but it wouldn't necessarily be required to be part of the editor. In fact it might be better if kept outside and reuse code from other content creation pages.
7. Source/HTML - I'd be in favour of and 'advanced' editing mode, although I don't think this would have to be a priority as most editors still would allow you to copy/paste from your favourite external editor. Not as streamlined granted, but equally why bother trying to replicate the best parts of everyones' favourite editors when people can still just use them right?

**Comment by tx4x** [comment]
hi,
3. images: please be careful with this one, writing a good tutorial or post needs some more options for images. apart from editing, one thing which always makes me mad (angry): the images in the bazar and anywhere else have quite poor quality, and worst, there is no way to open the full and original image in a new tab. just saying. your other points remain of course valid.

at the end I'd love to see real quality and lots of flexibility for users to write good content without any limitations, as seen in the Wordpress world were you can drag layout containers in place and drop in each of them some widget from a palette. I think there are already wordpress-less options out there for that, let me check, knowing already it comes with penalties and I am sure that at some point you guys will have to decide what's more important :  update to date top notch end-user authoring experience or serving developer preferences ;-) . I prefer the former, always, at any cost and even I have to plug some some older jQuery stuff :-)

let me know in any case what's your aim here; currently I'm rather looking at a good and advanced setup of TinyMCE. these guys put lots of experiences into there product, i can't see anything remotely in the more recent tech stuff....

**Comment by mattia-io** [comment]
Hey all,

@tx4x big up on all the research and summary, helps a lot 👍 

First of all I'd like to maybe clarify in which instances the text editor would be used:
1. User upload content (how-to, discussion, Q&A, events etc..)
2. User comments (newsfeed, how-to, discussion, Q&A, events )
3. Admin posts content (main news)
4. Can't think of any other instance, but maybe you guys have more scenarios in mind where it could be needed?

Commenting on the table @tx4x nicely created my feedback pretty much agrees with @chrismclarke in all comments. Few addition:
2. Not sure how much work this is but is def a nice-to-have feature
7. Didn't get this 😇

Nice one, let me know if you need more inputs from me.

**Comment by tx4x** [comment]
Hi,
alright then. as far i understood: we may have then 2 editors or let's say 2-3 editor configs : basic (only basic) aka 'quick reply' and 'normal' (writing a post). and more likely the available editor commands are controlled by ACL presets given by Mattia's mentioned contexts. if you like i can make a prototype with TinyMCE - community version. The very prototype should unveil the next corner questions: on how to proceed with a system wide ACL driven config (or whatever you want to name it ), and the required API end-points to make the tag and content picker (links) happening. Also, when creating a discussion, the entered title should already show possibly duplicates (queried and matched with the selected tags) which is basically already subset of the 'search' function. ( I'm pretty outdated about indexing and full text search, I know Elastic Search, Lucene, and Solr....)

**Comment by chrismclarke** [comment]
Sounds like a plan, will be interest to see what TinyMCE can offer (took a look at ck editor and their pricing is insane!). I see they have a wrapper for react already too: https://www.tiny.cloud/docs/integrations/react/

The api endpoints shouldn't be too difficult, will be happy to help with them once we have the core in place (probably makes sense to initially work with some mock data to see what type of format is easiest to work with).

Agreed on the title and searching, but all that is independent of the editor.  As mentioned above in this thread we plan to use algolia which will have good ways to handle this.

**Comment by chrismclarke** [comment]
also keep the code for draft so we can keep a comparison of the two. I definitely would be too quick to discount it, it's still a way more library:
https://www.npmtrends.com/draft-js-vs-react-tinymce-vs-tinymce-vs-tinymce-react
https://js.libhunt.com/compare-tinymce-vs-draft-js
Remember that the editor itself should be the easy part, the potentially more challenging will be adding the customisations we want, which could swing things either way.

**Comment by tx4x** [comment]
right, ok, let me try these days, we should have some results by Friday, i will put just a thin layer/abstraction between the editor and the core. no biggy. ah, thanks pointing out the algolia thing, forgot about already.
see you in a bit.

**Comment by tx4x** [comment]
in case you want to toy around: a tinymce wrapper is in place, open ::/discussion/create, this branch : https://github.com/tx4x/onearmy/tree/module--discussions, it's tinymce4x, and i must say it really feels alright compared to the draftjs thing.

**Comment by tx4x** [comment]
just as update: so there is no built-in support in the tinymce editor for now. there is also no clean way to convert html to markdown but vice-versa yes. so for powerusers a toggle button could enable markdown input and when saved, it outputs the html but then it has to save the markdown version as well. as alternative it could be just a 'import from markdown command'. that would do ok for me.

**Comment by chrismclarke** [comment]
thanks for the update. Assuming we get this in this week I think we can start some user testing at the workspace on Friday and pass any feedback along following. Most of the users here are unlikely to care as much about the advanced editing, but may have some useful comments more generally.

**Comment by chrismclarke** [comment]
I think this has been a really good conversation, tinymce is now integrated and working well so will close

**Comment by mattia-io** [comment]
Nice one. Thank you @tx4x 👊

**Comment by catx23** [comment]
bump,
might it be possible to add this at the end ? as it is now, we don't feel like making good articles without markdown and for now we're forced to go on with own tools (markdown -> stencil components -> html) - we could add add a few dozen good articles btw. 

since it's kind of plain text, you can still strip out easily html tags but allow a few such as hr, video, code,...

the route to get this is relative easy, if you don't have the resources I can add this as PR in the next weeks.

needless to say I guess - but Markdown has been quasi standard - and there's tons of good editors around...

thanks a lot.

**Comment by davehakkens** [comment]
i dont think we are ready to implement markdown or rich editors. yet. 
It's easy to implement but hard to implement properly.
Opens up to many possibilities and options to mess up the layout and create a mess.
Needs more thinking.

**Comment by catx23** [comment]
don't worry - you have 20 years skills in doing rich authoring software for the mass & experts at your hand ;-) I can't recall how often I implemented such things already :-)

**Comment by catx23** [comment]
the thinking part is btw. actually done on our end : https://github.com/plastic-hub/lang/blob/master/natives.md, one more iteration at best - pretty much all covered from what we and others need ..

**Comment by chrismclarke** [comment]
I really like markdown and am much more efficient with it, although at this stage I don't think it would have much use we are literally only using plain text inputs + image uploads in the platform to keep a very consistent style for all posts. The academy site is all markdown though.

**Comment by catx23** [comment]
Well, no problem. As alternative to the rather narrow and fixed structure now (steps need pictures), how about adding support for freestyle how-tos ? For instance, I just dump a markdown file and done :-) 

This way would we and others could could easily 'import' ready-to go content, more likely as seen in the almighty instructables.com way. That would allow users to be basically free and can focus on what's important in their articles rather than trying to fit it to a structure which seems often just in the way.
 
best,
g
