### ISSUE TITLE
How-to frontend

### ISSUE THREAD

**Issue by mattia-io** [OneArmyWorld/onearmy#234]
@charleenfei is working on this issue 🚀

The How-To page was designed in a rush to make sure we could at least gather content from users. We now have a more consistent UX design ready to be implemented. This will undergo a final design retouch later in the year. 

![Screenshot 2019-01-27 at 21.49.51.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5beadf2e66e72100136491d9/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416763e7b53e32a64c5b179f116224f5a5e5cb053181d1ba6acda6fb4bc2e75d80d58be8064597c946f14adbb821fb950bf218e4c87b7ae965e82b96371b8d6d6056b5c17129bfe553fa19c4fc05ef449e34d53a6113171ab.png)

Assets:
https://drive.google.com/drive/folders/1NnnIEpKY_UrWWCgB0CsavkUJUtZdsQ3g

Prototype:
https://sketch.cloud/s/KnZgA/WK2amx2/play

Recordit:
http://recordit.co/QrIFynXFIn

child of #3

**Comment by tx4x** [comment]
me as newbie would love to know a few things just : 
1. use @material-ui/core/createStyle over 'styled-component' ? 
2. where to add end-points in the back-end
3. patterns and code quirks ? ie: do we should use react's newer features such as 'useState' and 'useContext' in regard of more clean code, ie: functional programming (ramda?) and point free programming, see more https://www.youtube.com/watch?v=wXLf18DsV-I 
4. localization : where , what ,...how
5. policy when adding dependencies ? 

that's it for now ;-)

**Comment by chrismclarke** [comment]
1. Please describe the benefit/drawbacks of your suggestion so we can open it to discussion
2. There is a functions folder, see the index.ts for different ways backend can be interacted (http api, cron, triggers and called directly)
3. We do not have strong code requirements (a limited set is in the contributing guidelines). Essentially we expect all programmers to be responsible for writing their own clean code. If for any reason somebody feels a particular convention should be site-wide they should put the case forward as to why, and ideally be willing to support/review code of others trying to implement the same.
4. We started to create a module, however it's now been put in the backlog in favour of more pressing issues (quite frankly we're not sure whether we would have the capacity to keep a multi-language site well-maintained, especially in the early stages where lots of things are constantly changing
5. None (again expect devs to be responsible enough not to added tons of unnecessary bloat), although should make it clear when making a PR if it includes new dependencies (and briefly why).

**Comment by tx4x** [comment]
1. yeah, well i think it's an easy choice to use createStyle over styled-component : 

```ts 
const styles = theme => {
    return {
        button: {
            margin: theme.spacing.unit
        },
export const Component = (withStyles(styles, { withTheme: true })(CompoImpl));
```

rather than typing a long and error prone css text : 
```js
export const Title = styled.a`
  text-decoration: none;
  font-size: 1.1em;
  color: black;
  display: block;
  max-width: 100%;
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
  &:hover {
    text-decoration: underline;
  }
```

i can't say much about ups and downs of styled-component but i am pretty happy with createStyle which takes on the fly created theme parameters. another plus is wipe out another dependency :-) anyways, not much of a show stopper, do as you like

**Comment by tx4x** [comment]
mhmm, one last question :   i wanted to get active on the discussion editor and just realized that you don't use much material-ui after all, ie: no <Grid> (works great), <Button> or <Toolbar> but instead this style-components all over the place. i guess you want to keep it that way ?

**Comment by mattia-io** [comment]
@mattia-io I will be able to provide you with the mockups by the end of weekend for you to implement the new designs. 
For the style-component question, I leave it to @BenGamma to clarify

Big up!

**Comment by chrismclarke** [comment]
Thanks for the inputs @tx4x , all really useful. I'd be very excited if the createStyle can also handle the css priority issue (#179), but will leave it to @BenGamma to review as he's leading the css implementation.

As for material-ui, we initially imported it as a quick way to get up and running with some reasonable looking components. In the long term we will slowly be pushing for our own component library, taking from material-ui where it makes sense/saves time but really striving for our own distinctive branding. For some components/pages we've already migrated away, others are planned.

But it's all there for now so please feel free to use anything from library that helps you work in an efficient/productive way. It can easily be the job of somebody else to replace material buttons with our custom ones once fully defined (everything is still in settling phases/various states of flux, so priority is on keeping things driving forward and not worrying too much about things that can be resolved reasonably easily in the future). 

We will definitely want grid as we focus on mobile design (another one that has been put in the backlog but design team have started working on), so if that's something you want to use then please feel free. If we later decide that actually it will be easier to handle flexible layout through flex and component display parameters then we just change then, although having examples of grid definitely helps move the debate (and the project) along, so win-win. 

In addition I would suggest you quickly check #93 which explains a small quirk when importing which can dramatically impact on build times

As a quick (final?) comment, I would just like to try to communicate that for the most part the way that we operate is aspirationally akin to a pragmatic-yet-informed democracy. We want to create a product that we can be proud of, and that many people will be able to use for years to come. As an open-source community we have a wide variety of opinions for how this can be achieved, and no formal mechanisms for ultimate decision-making nor changes (for code at least, design we have stronger influence). Up till now the general flow is that people do things, then if for some reason somebody suggests an alternate way to do then we quickly debate, decide, and move on. So whilst many things have been properly discussed (e.g. ditching redux for mobx or scss for styled-components), many others are simply the result of people working in the manner they are most accustomed to (e.g. react classes vs functions, hooks etc.). Some things are now pretty uniform throughout the project, some things will hopefully be in the future and some things will likely never be. 

Ultimately if you think there is something that would benefit a wider community then we encourage you to make the case for it (i.e. we should use this because it will help/allow/enable xyz (and ideally not 'because I've used it before and like it' - we're all here to learn together). However every change falls directly on the heads of those implementing them (up till now it's a very small number of people who have been writing the core code), and so if you're also willing to be the one to lead on the implementation side then that is welcomed most warmly. We sincerely appreciate your thoughtful comments up to now and would like to encourage you to keep bringing ideas (and code!) forward.

**Comment by tx4x** [comment]
@chrismclarke  ok, great! Will go with the material-ui components then, as well doing it the pure component / FP / React-hooks - way. As far I understood we won't touch unit or function tests (i am fan of puppeteer with cucumber-testing in top (i have some tooling done for that as well in place).

**Comment by chrismclarke** [comment]
I really want to get some e2e tests going at some point so +1 to puppeteer! (Personally don’t value unit tests as highly when there’s already typescript + common sense, but if anyone wants/is willing to push forward an agenda then please feel free).

**Comment by BenGamma** [comment]
@tx4x Like Chris says we use material-ui as a quick implementation of a component based frontend structure. But in the futur, we will have our own components and styled-component seems to be the best solution so far for the job.

Personaly I'm more willing to start building styles using styled-component right now to make the transition easier when the design will be ready to implement.

So about your question on "styled-component all over the place" yes, I think we should keep it. You can easily combine both thought, by overwriting material-ui components as answered here https://github.com/styled-components/styled-components/issues/1253#issuecomment-337871693

**Comment by mattia-io** [comment]
Assets have been updated (big up saskia ❤)
And Charly took on this issue 🚀

**Comment by semeano** [comment]
@BenGamma have you considered [BEM](http://getbem.com/)?

**Comment by chrismclarke** [comment]
> @BenGamma have you considered [BEM](http://getbem.com/)?

@semeano , thanks for sharing your thoughts although if possible could you please follow the guidance from the [contributing guidelines.](https://github.com/OneArmyWorld/onearmy/blob/master/CONTRIBUTING.md#-why-havent-you-used-insert-favourite-languageframeworkconvention-here)

Specifically, start with why you think something (BEM) would be better than what is being used (Styled Components).

P.S. There's already a pretty interesting discussion on the topic at the link below, although if you have some of your own personal opinions for our community then it would be great to hear them.

https://spectrum.chat/styled-components/general/bem-sass-vs-styled-components~34b75b86-273d-434f-bc2b-dbb847678e89.

**Comment by chrismclarke** [comment]
Hey @mattia-io , quick question - have we settled on the fonts for the project? @charleenfei has been exploring ways to import additional fonts for use in the how-to frontend so would be good to know what current suggestions/restrictions are.

**Comment by mattia-io** [comment]
hey @chris, 
yep was passing @charleenfei Karla font as it is the working font for the time being.. 
still looking into smart ways of reducing data requests due to fancy font :)

I understand that might cause some conflicts with the rest of the site.. 
Can we easily switch to Karla to keep it consistent between mocks and prototype? Or is it a big pain in the ass?

**Comment by chrismclarke** [comment]
I don't think you have to worry too much, a custom font really doesn't add very much overhead and can quite easily be swapped in and out - everything related to fonts sits in the same folder and connected with a single line of code (specifying the theme), so any changes can be implemented very easily. So I would suggest just proceed with whatever keeps us consistent with UI team. We can also specify a fallback in case anybody is using a super-old browser (Although I feel if someone is using IE8 fonts are the least of their worries)

**Comment by chrismclarke** [comment]
@charleenfei - I'm pretty sure your PR already was set to use Karla across the entire site, but if not could you please make it so it does?

**Comment by mattia-io** [comment]
Sweet.. here is the font
[Karla.zip](https://github.com/OneArmyWorld/onearmy/files/2859432/Karla.zip)

**Comment by BenGamma** [comment]
Closing. Now discussed in up-to-date #419
