### ISSUE TITLE
Review styled-system implementation

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#237]
Suggested by @PepijnSenders 

https://jxnblk.com/styled-system/
could build on top of our styled-components

Let me know what you think @benj

**Comment by PepijnSenders** [comment]
Related discussion: https://github.com/OneArmyWorld/onearmy/pull/231#discussion_r251344575

**Comment by BenGamma** [comment]
Thanks for bringing this under the light @PepijnSenders. This solution seems a nice way to deal with styling.
As chris said in the discussion, the styled-component system is still a current work in progress, I'm exploring a lot of ways as I've never built such a UI system out of it.
I kind of link the styled-system approach, the fact that we get rid of the elements.js file in the current component folder.
My only fear is that it adds one more layer of abstraction in our codebase, and it seems to me a bit more complex to understand for new comers (since it has a lot of shorthand syntax).

My current idea of styled-component implementation is to create the maximum reusable basic components in `src/components` and then import them and adjust/customize from the `src/pages/<page>/<component>/elements.js`. That way it helps reducing the size of the files inside a component and keep the separation betwen `js` related files and `css` (in js 😅 ) related files (which I kind of like, but that's personal). The last thing is that it reduce the number of props given to a component. In my opinion too much props can lead to confusion between styling related, state related or data related props.

But again we are open to discussion and as @PepijnSenders you seem to have a bigger experience in building big app using this stack, it make sense to choose the most used implementation of styled-components.
Would you say that in the react world it's more common to style using props ? or using a element.js file inside each component ?
As a example [spectrum.chat](https://github.com/withspectrum/spectrum) and [codesandbox.io](https://github.com/CompuIves/codesandbox-client) are using an element.js file based. But maybe you know some examples with styled-system in other big plateforms ?

**Comment by chrismclarke** [comment]
I think the biggest challenge you will have is how much to populate automatically and how much manually. E.g. do we want a `<DownloadButton>` component that will always have a download image icon and be styled the exact same, versus a more general <Button> component which can take the icon as a child component, or meet somewhere in the middle like material-ui does with things like variants.

**Comment by BenGamma** [comment]
Yes, I detailed the new behavior of the button component in https://github.com/OneArmyWorld/onearmy/pull/242
Yesterday I fell on this article about styled-system and I found it very interesting : https://medium.com/styled-components/build-better-component-libraries-with-styled-system-4951653d54ee
I really liked the approach and will definatelly keep it in mind for the futur

**Comment by BenGamma** [comment]
Hey @PepijnSenders, I tryied an implementation of styled-system last week, and that was a good experience. I liked the consistency that it gives to build the interface and I think it can be a good choice since a lot if different developers will work on the interface.
You can have a look on the new branch `feature/styled-system-test`

It makes a lot of sense for building the layout boxes, container, margins, etc but I'm a bit more confuse when styling an precise object like button, should I move all the css from for example `src/components/Button/elements.js` to the buttons object in the theme ?

if you can have a look and give me some feedback it would be nice, thanks !
