### ISSUE TITLE
add text formating options

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#30]
Enable the writer to style his text with bold, italic, heading, etc

**Comment by chrismclarke** [comment]
Does this mean you are going back to the idea of a html wysiwyg editor? I saw a few react ones already around. Otherwise you could look into something like markdown

**Comment by BenGamma** [comment]
I like markdown but it is maybe more a developer things. It make more sense to me to have a wysiwyg editor to avoid confusion/complexity for our user

**Comment by chrismclarke** [comment]
I think either system could be made easy enough, assume we want a very limited set of options you can compress a cheat sheet for markdown into 4 or 5 lines (pretty much what I tried to explain in  #2 ). Html gives more flexibility and can also be neatly limited (removing buttons from the standard editor if we don't want people to be able to change colour for example). I can see either working so I guess just see which you prefer working with. 

The react html editor created by facebook is: https://github.com/facebook/draft-js , which might do the job nicely

Otherwise there seems to be no shortage of react markdown render components (although haven't tested any)

**Comment by BenGamma** [comment]
I've worked with a markdown implementation in react but it was really messy, maybe there is proper library now, but if not, i'll go for the html editor

**Comment by BenGamma** [comment]
Closing, now discussed in https://github.com/OneArmyWorld/onearmy/issues/211
