### ISSUE TITLE
differentiate between 'dev' and 'dev' sites

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#316]
currently the dev site is a bit misleading as it serves as a staging site and runs a production build. The platform needs to distinguish between localhost dev, staging dev, and production site so that data and additional view components can be handled correctly

Will add a quick fix now

**Comment by chrismclarke** [comment]
@tx4x - I know a few of the features you were working on used this functionality. If you get the chance could you quickly check the implementation to see if you are also happy with it

**Comment by tx4x** [comment]
yeah, that looks right to me :-) anyways, don't bother too much about what I like, i am just a volunteer ;-)

apart from the config switch and only as personal preference I am used to fetch app configs at run-time but only because i've done the apps via a node-express server which replaces variables in templates and also returns seed keys or tokens to sign  RPC callsbut i guess we don't need it :-)
g

**Comment by chrismclarke** [comment]
Haha, in the same boat here! I usually try to give a heads up when making knock-on changes, if for no other reason I won't have to resolve conflicts later :D

The system is there if we wanted to fetch configs, it's what now happens on the backend (Travis sets additional firebase variables during the CI deploy stage (see src/scripts), and actually if full dev/prod config set there we wouldn't have to worry about anything else. Although that ties us more closely in with firebase so probably not worth the effort.
