### ISSUE TITLE
Discussion backend

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#344]
Need CRUD operations for discussions, as well as listing discussions, comments, and individual docs

child of #213

**Comment by chrismclarke** [comment]
In Progress, hope to complete by Tuesday

**Comment by RangerMauve** [comment]
Hi, I really like the effort you're putting into making a usable tool for decentralized organization.

One of the focuses that stood out to me was the focus on making things work offline in addition to offline.

With that in mind I was wondering if you'd be interested in integrating P2P technologies instead of a traditional centralized back-end in order to give users of the tool more power over their own data and to open up use cases for working offline or over local networks.

I'm coming from the [Dat](https://datproject.org/) community and organizing people in decentralized systems is something that I've been thinking about a lot. Specifically, how do we build systems that are truly operated by their users, don't rely on large corporations like Google or Amazon for hosting, and don't require communities to set up their own hosting infrastructure (thus more centralization that can go down).

With Dat your building block is a folder that people can store their data in, and share over the P2P network using a URL. The idea is that only the owner of the Dat Archive can update it, but anybody that's downloaded a copy of it can share it to others that might need it. This is a useful building block for decentralized and offline-first systems because a person can add things to their archive whenever they want, and sync it out to others once they're connected to the internet or through local WiFi hotspots.

I think that using Dat for your data layer can make your software more versatile, and will help communities stay independent of large corporations that could impose arbitrary costs and restrictions on them.

**Comment by BenGamma** [comment]
@RangerMauve just moved your question in a dedicated issue #374

**Comment by BenGamma** [comment]
closing since part of discussion module
