### ISSUE TITLE
Form packages

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#37]
We have a few places where we need forms, the first being the documentation tutorial section. Currently we have been using react final form, another recommendation is formik. Both seem to have strong advocates, my impression seems that formik is a little bit simpler/more familiar for react, react final form perhaps more performant/scalable.

I think both would be solid choices and can't imagine potential limitations being reached in either case. Probably best to experiment and see if can get either to work quickly.

Links to related discussions:
https://github.com/jaredpalmer/formik/issues/533
https://www.npmtrends.com/formik-vs-react-final-form

**Comment by chrismclarke** [comment]
additional, handling arrays:
https://github.com/jaredpalmer/formik/issues/510
https://github.com/final-form/react-final-form-arrays

**Comment by SpaceK33z** [comment]
I have used both Formik and React Final Form and would definitely recommend Formik. Mostly because it is written by TypeScript and thus will always have the best TS support. The author of Final Form doesn't use TS himself so they rely completely on contributors for that. That being said, with Final Form you also can't really go wrong.

**Comment by chrismclarke** [comment]
I agree, although as we currently only have one set of components using Final form which is working as desired it makes sense to keep for now (but change if we start to need more). Thanks, closing
