### ISSUE TITLE
Use of GraphDB to provide recommendations

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#391]
Ben (yet another one!) from the community recently reached out to discuss use of graphDB to link into a recommendations system. It would be good to use this issue to share any thoughts on this. Could you outline your thoughts and investigation so far **Ben**?

**Comment by 007vasy** [comment]
The idea is to build a graph based recommendation engine for the bazar.

[Here is how](https://www.kaggle.com/ironben/rdbs-to-graphdb-neo4j-network-approach)
[Tech example](https://neo4j.com/developer/guide-build-a-recommendation-engine/)

**Comment by chrismclarke** [comment]
I think at this point my impression is that it's something interesting but wouldn't be a priority. Once working with some mock data we can look at what data from the platform you might want to access and the best way to do it.

**Comment by 007vasy** [comment]
What do you mean by "Mock data"? The kaggle thing was written by me :D

**Comment by BenGamma** [comment]
The mock datas are lorem ipsum data for development purpose only.

Be sure to check our [contribution guide](https://github.com/OneArmyWorld/onearmy/blob/master/CONTRIBUTING.md) to understand all our current codebase.

**Comment by 007vasy** [comment]
So I did a recommendation engine on kaggle as a proof of concept and you want me to do it with dummy data? Or do you mean figure out your database structure from the code make a lorem ipsum data then show it to you?

**Comment by BenGamma** [comment]
Hey @007vasy,

I checked your links below, it sounds like a lot of work, I guess you've learned a lot out of it.

But it is hard to understand for someone without any tech background in data science and/or the use of the tools your described in your kaggle.

To be straightforward, we are not planning on working on preciousplastic bazar for now, there is already a lot to do with building the onearmy plateform.

If you would like to help in any way you can check the issue board of the repo, but I'm going to close this issue, since we are not planning on building a recommandation system in a close futur.

Thanks for the work and keep it up 💪
