### ISSUE TITLE
Code Review - Home page and login components

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#41]
Requesting a review of the home page and login components.

The home page sits within the main router at `pages/index.ts`. It has state typings inline and renders two different divs dependent on whether the user is logged in or not (will later be built out with components). I've created a test user that can login with userrname and password both matching 'test@onearmy.world'.

The login component sits inside a container which has bindings to get/set global state. Together they handle a number of things including communicating with the auth service, reflecting changes back to the global redux state as well as notifying up to parent component (in this case home page) - this might seem counter-design as standard model would be to read down from the global state and wrap the home page in a container to pass the property (currently feels overkill, but likely useful in future when more state read).

Could you check if the code seems organised logically and is reasonable to follow/maintain?

**Comment by SpaceK33z** [comment]
Nice!

First off a question: have you looked at using [MobX](https://mobx.js.org/getting-started.html)? Redux can be very tempting because it is used so much, but every project I've ever seen turns into a mess because of the insane amount of boilerplate. And then there's the performance argument; MobX only re-renders when something actually changes in a component. This is slightly off-topic tho.

But anyway;

- In `src/containers/`, why is the Login container called `Login.container`? It's already in the `containers` directory, so that seems a bit redundant. Same thing with models.
- In `src/models/models.tsx`; I don't understand why this naming scheme is used. I'd either rename it to `index.tsx` so you can just do `import {...} from 'models'`, or maybe remove this altogether; importing a specific model is easy enough without this file altogether, plus in a large team it can introduce merge conflicts.
- I see you're not using internationalization tools. If you're sure the intention is to never translate the site into multiple languages this is fine, but if there is even some doubt I'd use i18n tools. In my experience converting an app from no i18n to using i18n is very time consuming.
- The strategy used to override Material UI styles [here](https://github.com/OneArmyWorld/onearmy/blob/24e761204dff535bb1d0204605ee4881bf088f6a/src/components/Login/LoginForm.tsx#L25) by using inline styles is not really sustainable I think. I'd create separate components like for `<Form />` and override the styles in there by using class names.
- Clarify somewhere in the README what browsers you intend to support. I'd advise to not support faded glory like IE11 because anyone using this site is smart enough to update their browser (an assumption ofc).
- I have never really used Firebase for a project so can't say anything about that.
- The container/component structure is a good idea.
- Good job on the contributing guide!

Hope this is useful!

**Comment by chrismclarke** [comment]
Really useful thanks!

I looked into MobX, seemed general consensus was it was easier but doesn't scale as well. I ended up going with the advice from [article](https://codeburst.io/mobx-vs-redux-with-react-a-noobs-comparison-and-questions-382ba340be09) and stuck to redux as it's something I've used a lot before (although I really hate how much boilerplate there is, angular-redux is much simpler).

Login.container is because quite often you will be working with both the container and child login components simultaneously, and I hate tabs named 'Login' and 'Login' - currently components and pages reserve simplest naming conventions and then anything else like models, sagas, containers, apis etc. will have additional naming. I'd like to avoid the same situation with index.tsx files (I once saw @BenGamma with around 10 'index.tsx' tabs open at the same time and felt close to mental breakdown) so think a sensible compromise would be to have index.ts files in each folder which only import and export other components (i.e. pages/index.ts will contain references from pages/home/home.tsx and pages/docs/docs.tsx, so you can still import from 'pages' but if refactoring both pages you would have have home.tsx and docs.tsx open), created #46. 

We had internationalisation suggested and generally agreed upon (just with different senses of priority). I saw there were some good packages already for this and seeing as I've just spent the past 3 days backdating translations in another app I'm working on agree we should get this in place sooner. added as #45

Agree on unsustainable styling. Was suggested using: https://www.styled-components.com. I haven't tried but @BenGamma said he will try to do so and see how it goes.

IE11? will add support right after I get round to netscape (bringing <blink> back). Readme updated

Thanks again!
