### ISSUE TITLE
files upload limit ?

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#42]
Define a file size limit on documentation, for uploaded images and files.
I guess for images it will be a few mo, but for the project files (3D models or other files needed to achieve the tutorial), we need to define a bigger upload limit.
Probably need to discuss with Dave & our beta users.

**Comment by chrismclarke** [comment]
We don't want to be hosting giant files. You should have a sensible limit (maybe 10MB?) and also let the user simply provide a link to a file hosted elsewhere. I.e. next to the uploader have (max file size 10MB) and 'or paste download link' input box with 'add' button or similar. The logic for pasted links would be pretty similar to the file uploader, but instead of waiting for upload callback to get href you can just push it direct to the links array.

**Comment by BenGamma** [comment]
After discussion with mattia and saskia, we'll defined a file upload limit (probably between 10 and 20mb) and a new field to provide external links as suggested by @chrismclarke .
Need wording for user information.
