### ISSUE TITLE
[feature request] Connect with wechange.de and Karte von morgen (map of tomorrow)

### ISSUE THREAD

**Issue by wellemut** [OneArmyWorld/onearmy#426]
In Germany, there are allready some of those plattforms starting, and Initiatives would like to find all projects on one place, and not scattered all over different tools.

wechange.de is an open source, collectivley owned, privacy secure and non profit plattform, which helps projects to collaborate online. 

KartevonMorgen.org (Map of Tomorrow) also is a non profit crowd developed online map to make tranforming initiatives visible. https://github.com/flosse/kartevonmorgen

Both projects will merge in the summer, to build the best online solution for transition.

**What do you think about joining forces and develop something together?**

My Contact: Helmut Wolman, Helmut@bildungsagenten.com, 01573-4448245

**Comment by chrismclarke** [comment]
Hi Helmut, thanks for reaching out and for the links to the really interesting projects. A personal response from me, which I'll keep brief and in this thread just so that it's open to anyone else who also wants to add.

I definitely know there's no shortage of good, open-source projects fighting the same battle as the onearmy community, and although I can't speak for the community as a whole I can say that everybody I've met so far has been very open to collaboration and moving forwards together.

That being said, there is always a huge challenge of aligning different technologies, groups, targets etc. I see that the main we-change repo is predominantly python/django based and we're taking a full javascript approach at the moment. I see kartevonmorgen is mostly based on JS/React/Leaflet which has been our proposed trajectory for maps so I think there would be stronger opportunities there (I'm interested to hear how you plan to merge the two platforms together). 

I think our platform still has a bit of maturing to do within its current development cycle, to at least get to the stage where we have a solid, consistent architecture and then we would be better-placed to discuss how specific modules could become specific points of collaboration. But as part of our ethos and future sustainability I think the types of partnerships you've mentioned are really important.

**Comment by chrismclarke** [comment]
For housekeeping I'm going to close this conversation for now, but I've added reference to it on the wiki page: https://github.com/OneArmyWorld/onearmy/wiki/Reinventing-the-wheel-(collaborations)

Also anyone can still feel free to add comments to this thread

**Comment by wellemut** [comment]
Thanks for your anwer @chrismclarke !
I definitly understand this questions of different technologies. Therefore Kartevonmorgen will allway stay an on JS/React/Leaflet project, linked via ActivityPub to wechange. Thats our actual state of development.
