### ISSUE TITLE
friend community, we are another one army called human pixels 

### ISSUE THREAD

**Issue by oceatoon** [OneArmyWorld/onearmy#430]
Hi 
I just discovered your project , it's great , and looks a lot like our communecter.org in production since 2016
we used to be called human PIxel https://vimeo.com/74212373
but as we've been growing we work a lot with the commons , we changed name to communecter 
which means connecting the commons https://vimeo.com/133636468
I'd love a bit more information , is there a place to see the wireframes or workflow 
maybe we can help you guys , and join armies ;)

**Comment by oceatoon** [comment]
Hi @chrismclarke  and @BenGamma 
yes and always have been , we have 2 stacks both based on a mongoDB 
the web version is a php , jquery 
the mobile , tablet version is oriented real time activity is NodesJS, meteor 
we have a modular and API driven architecture which is open to any stack
we also follow the fediverse connectivty standards like activityStream 
would be great to hook up at least for a peacefull army chat 
what are your availabilities ?

**Comment by tx4x** [comment]
@oceatoon , nice nice. looking at the project and [code](https://github.com/pixelhumain/communecter) I see lots of overlap with onearmy and as a occasional contributor I'd rather say that onearmy focusing more on making knowledge accessible,editable, manageable first rather than actually connecting people as seen in 'communecter' (later though), i can be wrong of course ;-)

However, exchanging detailed data models, specs for user, locations, events, resources, articles, organizations, etc... would indeed help solving onearmies latest problem dealing with a new backend (database, REST,...). There's lots to do in this direction, I am sure that @oceatoon's experience in that matters would help to narrow it down to further concrete steps. Such models can be created with [Swagger tools](https://petstore.swagger.io/), or any other tool ( i like enterprise architect). To add a little more large-scale taste, it can't harm to checkout 'Liferay' CE portal source code which covers pretty much all needed to run communecter or onearmy globally.

**Comment by BenGamma** [comment]
Hi @oceatoon and thanks for your comments !
I went throught communecter.org and that's always interesting to discover others similar project as onearmy. Also thanks for pointing out Fediverse, I've already knew a few project of the federation (mastodon or diaspora) but I didn't know they where based on a common protocol (activitySub). That opens a lot of possibilities for the futur.
As @tx4x mentionned, onearmy platform (in it current shape) is more about sharing knowledge and technics, rather than social. But in a close futur that could also be an option.
I truly agree with you on the fact that we could/should join forces and I would be keen on having a chat about it. You can contact us at hello@onearmy.world and we'll try to schedule this.

@tx4x thanks for the pointing out swagger, it looks likes strong guidelines 💪

**Comment by oceatoon** [comment]
all this is super
I'll send a mail to set up a call
we use swagger for our api endpoints
https://www.communecter.org/api
it's really made for APi Restfullness

**Comment by tx4x** [comment]
if you guys like, i can join and may be add 2 cents :-)
'zoom' would be great

**Comment by BenGamma** [comment]
Can you provide an email @tx4x so I can invite you to the call ? Will be this wednesday 11AM GMT+02

**Comment by tx4x** [comment]
@BenGamma  cgoflyn@gmail.com, see you then, i guess it's on 'zoom' then.

**Comment by tx4x** [comment]
@here, i am doing mentioned the liferay/communector sample instances over weekend :-)
g

**Comment by tx4x** [comment]
@BenGamma do we have roadmap ? just wondering what to plug in liferay and communector ...

I know only of : 

- how-to
- discussions aka forums
- events

in our reality we want : 

- how-to, versioned (community updates, etc...)
- discussions, chat, per continent
- library (molds, ...), with upstream to store, per region
- store, with CRM for sellers, per region
- streams (curated, instagram, google bots,...)
- contacts, per region
- organizations, yet flat
- events, ...per region, language
- a button to set the project manager's chair under electricity

**Comment by BenGamma** [comment]
Hey @tx4x,
I can't provide you a roadmap as precise yet. As I said on the phone I can't assure you that we would use the liferay connector you are building.
I would say do the thing that correspond to your needs for precious-plastic.org for now and we'll do our best to found ways to plug in with in the futur.
I'll keep the github updated and the maximum transparent as I can on what we are working on, so we're all on the same page.
Thanks for your feature suggestion by the way, a lot of pertinent points. I'll keep them. I'm not sure about the electric chair though 😅
