### ISSUE TITLE
[bug] - tags don't appear on live

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#500]
**Describe the bug**
Tags are uploaded to dev site via temporary script which can't be easily replicated onto live. Therefore method will be needed set the live tags

**Comment by chrismclarke** [comment]
creating an admin page where this can be done programatically

**Comment by chrismclarke** [comment]
PR made for admin pages, once live can use admin page button on live to update

**Comment by tx4x** [comment]
@BenGamma , @chrismclarke , @mattia-io ; once again you target us with defamation, creating exposure  to public hatred by your fanboys with clear intentions to harm as in many ways you can possibly do, without any prior consensus. 

if this video is not down and/or replaced without the kids play removed; i have no other choice to involve legal actions but also forcing me to come to Eindhoven today.

let me remind you that your kids play has consequences, being carried out by young families of our team here with little to no means. 

I take this very very serious; if you push us here over the edge; there is no return for you @davehakkens

**Comment by tx4x** [comment]
ok, then. we're heading for Barcelona; let me make it clear that I hold you responsible for all consequences carried out the families here working on PP.

**Comment by tx4x** [comment]
@mattia-io , @BenGamma , @chrismclarke

**Comment by tx4x** [comment]
@mattia-io , @BenGamma , our lawyer confirmed, every hour this video is online is going to be expensive for you; it can't be that you punish and harm our people here just because you can't deal with critics and opinion and put us on the stage for hatred as seen now on youtube.

i just can hope there is a single slice of decency in you to stop this; count on me taking this very very serious

**Comment by Jerzeek** [comment]
@catx23 Sorry but I think your reply is not related to the issue, would you please be so kind to delete your comments here.
If the problem you are describing is still an issue, you could think of opening a new issue. Even though I think your problem is not related to the digital development of OneArmy

**Comment by chrismclarke** [comment]
build live, tags updated, closing
