### ISSUE TITLE
Display tutorials in chronologic order

### ISSUE THREAD

**Issue by BenGamma** [OneArmyWorld/onearmy#54]
* maybe a firebase method exist to get tutorials in chrono order
* if not add createdAt field when creating a tutorial (it can be useful to have it anyway)
child of #3

**Comment by chrismclarke** [comment]
Firebase by default links unique id to a timestamp to retain chronological order, however I still suggest we have fields for ‘created’ and ‘lastModified’ to be able to track recently changed.

It also makes sense to couple this with limits so that firebase doesn’t pull all data each time (we could include something like an infinite scroller to trigger next batch of data pull as the user scrolls, or on the click of a ‘more’ button at the bottom)

https://firebase.google.com/docs/database/web/lists-of-data
